name: PrisonControlPickaxes
main: com.mrlubert.prisoncontrol.PrisonPicks
version: 1.2.1
api-version: '1.20'
description: PrisonControl Plugin
author: MrLubert
depend: ['WorldGuard']
softdepend: ['AutoPickup']
commands:
  pick:
    description: Main Command
permissions:
  picks.explosive:
    description: Allows you to spawn in the various Picks
    default: op
  picks.reload:
    description: Allows you to reload the config
    default: op
  picks.repair:
    description: Allows you to hide the repair messages
    default: true